#! /bin/bash

rm chess3d.zip

echo "<div class='version'>version: $(date +%s)</div>" > ./src/app/version.html
npx ng build --configuration=production --base-href /chess3d/

zip -r chess3d.zip chess3d
# rm -rf chess3d
