#! /bin/bash

rm chessGL.zip

echo "<div class='version'>version: $(date +%s)</div>" > ./src/app/version.html
npx ng build --configuration=production --base-href /chessGL/

zip -r chessGL.zip chessGL
# rm -rf chessGL
